USE gom;

CREATE TABLE Sessions(
Sid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
sessionName TEXT null,
Creator TEXT null,
numPlayers INTEGER,
NumSentences INTEGER,
NumCurrentPlayers INTEGER,
numOfSubmits INTEGER,
Closed TINYINT,
sessionIsFull TINYINT,
PRIMARY KEY (Sid)
);

CREATE TABLE Players(
Pid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
playerName TEXT null,
playerPass TEXT null,
Turn TINYINT null,
Sid INTEGER UNSIGNED NOT NULL,
PRIMARY KEY (Pid),
FOREIGN KEY (Sid) REFERENCES Sessions(Sid)
);



CREATE TABLE Sentences(
Vid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
Value TEXT null,
lastWord TEXT null,
Pid INTEGER UNSIGNED NOT NULL,
Sid INTEGER UNSIGNED NOT NULL,
PRIMARY KEY (Vid),
FOREIGN KEY (Sid) REFERENCES Sessions(Sid),
FOREIGN KEY (Pid) REFERENCES Players(Pid)
);


CREATE TABLE Sessions(
Sid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
sessionName TEXT null,
Creator TEXT null,
numPlayers INTEGER,
NumSentences INTEGER,
NumCurrentPlayers INTEGER,
numOfSubmits INTEGER,
Closed TINYINT,
sessionIsFull TINYINT,
PRIMARY KEY (Sid)
);

CREATE TABLE Players(
Pid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
playerName TEXT null,
playerPass TEXT null,
Turn TINYINT null,
Refresh TINYINT null,
Sid INTEGER UNSIGNED NOT NULL,
PRIMARY KEY (Pid),
FOREIGN KEY (Sid) REFERENCES Sessions(Sid)
);



CREATE TABLE Sentences(
Vid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
Value TEXT null,
lastWord TEXT null,
Pid INTEGER UNSIGNED NOT NULL,
Sid INTEGER UNSIGNED NOT NULL,
PRIMARY KEY (Vid),
FOREIGN KEY (Sid) REFERENCES Sessions(Sid),
FOREIGN KEY (Pid) REFERENCES Players(Pid)
);

